### ISSUE TITLE
Alpha Vantage Down for Italian stocks?

### ISSUE THREAD

**Issue by lorenzo-gabrielli** [PatrickAlphaVantage/alphachain.io.website#1]
Hi,

I read you are a developer advocate for Alpha Vantage.
last week there have been some API malfunctions that seem to have not yet been resolved (the bees are returning empty results for Italian actions to even British ones). Did you know anything about these problems?

I wrote to alpha vantage support but no one showed up.

Best
![alpha vantage](https://user-images.githubusercontent.com/18683450/85982090-88ae6000-b9e5-11ea-9ff9-090f1bc159c1.PNG)

Lorenzo

**Comment by PatrickAlphaC** [comment]
Thanks for pinging me here. At the moment, I'm part time with the alpha vantage platform. There have been some issues recently with global tickers. They are working on a fix, we apologize for any inconvenience.
